name: Main Tests

on: [push, pull_request]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Isofit
      run: |
        python -m pip install --upgrade pip
        pip install --editable . --use-feature=2020-resolver

    - name: Run Test
      run: |
        pytest

